### ISSUE TITLE
LogInit: Error: FLinuxApplication::CreateLinuxApplication() : InitSDL() failed, cannot create application instance.

### ISSUE THREAD

**Issue by wangchangquan** [autonomousvision/data_aggregation#3]
when i run the comand :python3 multi_gpu_collection.py -ids 0 -n 1 -g 1 -e 10 -pt /data2/data_aggregation -ct carlagear -m expert
i meet the issue
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
using gpu id:  0
ERROR:root:(localhost:10000) connection closed
ERROR:root:(localhost:10000) connection closed

for a long time...

and i found the carlagear not run ,when i use "docker ps".

then i run carla in a docker  singely ,use command :docker run -it --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 carlagear /bin/bash CarlaUE4.sh /Game/Maps/Town01 -windowed -world-port=10000  -benchmark -fps=10.

and printed the error:
[2020.09.17-18.03.28:033][  0]LogInit: Error: FLinuxApplication::CreateLinuxApplication() : InitSDL() failed, cannot create application instance.

I use Xshell to log in a server do this work, and not have gui to display. 
so How to solve this problem.  thanks a lot.

**Comment by ap229997** [comment]
I have never observed this issue in Ubuntu 18.04. Can you tell me which Linux version are you using?

**Comment by wangchangquan** [comment]
I solve the problem.
the reason is run the code in a remote nodesktop server ,but the carlagear is a displayable docker. so should shut down the display in carlagear.   I change the code,**add the env 'SDL_VIDEODRIVER=offscreen'**

def open_carla(port, town_name, gpu, container_name):
    sp = subprocess.Popen(
        ['docker', 'run', '--rm', '-d', '-p',
         str(port) + '-' + str(port + 2) + ':' + str(port) + '-' + str(port + 2), '--gpus=' + str(gpu), '-e', 'SDL_VIDEODRIVER=offscreen', container_name,
         '/bin/bash', 'CarlaUE4.sh', '/Game/Maps/' + town_name, '-windowed',
         '-benchmark', '-fps=10', '-world-port=' + str(port)], shell=False,
        stdout=subprocess.PIPE)
    (out, err) = sp.communicate()
    return sp, out

**Comment by ap229997** [comment]
That is a little weird since I have also been running this on a remote server without display and it always worked fine without any issue. Anyway, good to know that it works fine now so closing the issue.
